/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import controlMySql.MySqlConn;
import javax.swing.JOptionPane;



public class Servicios extends javax.swing.JFrame {
    
    MySqlConn conn=new MySqlConn();
    private int sum=0;
    
    
    public Servicios(MySqlConn conn){
        this.conn=conn;
        initComponents();
    }

    /**
     * Creates new form Servicios
     */
    public Servicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxCuart = new javax.swing.JCheckBox();
        jCheckBoxBar = new javax.swing.JCheckBox();
        jCheckBoxTintoreria = new javax.swing.JCheckBox();
        jCheckBoxSpa = new javax.swing.JCheckBox();
        jCheckBoxNiñera = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jTextFieldHabServicios = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("CONTRATAR SERVICIOS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(221, 13, 280, 29);

        jCheckBoxCuart.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jCheckBoxCuart.setText("Servicio a Cuarto");
        jCheckBoxCuart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCuartActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxCuart);
        jCheckBoxCuart.setBounds(287, 128, 147, 27);

        jCheckBoxBar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jCheckBoxBar.setText("Servicio al Bar");
        jPanel1.add(jCheckBoxBar);
        jCheckBoxBar.setBounds(287, 192, 127, 27);

        jCheckBoxTintoreria.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jCheckBoxTintoreria.setText("Servicio de Tintoreria");
        jPanel1.add(jCheckBoxTintoreria);
        jCheckBoxTintoreria.setBounds(287, 258, 175, 27);

        jCheckBoxSpa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jCheckBoxSpa.setText("Servicio de SPA");
        jPanel1.add(jCheckBoxSpa);
        jCheckBoxSpa.setBounds(287, 326, 141, 27);

        jCheckBoxNiñera.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jCheckBoxNiñera.setText("Servicio de Niñera");
        jPanel1.add(jCheckBoxNiñera);
        jCheckBoxNiñera.setBounds(287, 392, 155, 27);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Habitacion:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(287, 89, 79, 19);

        jButtonConfirmar.setText("CONFIRMAR");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConfirmar);
        jButtonConfirmar.setBounds(132, 441, 120, 23);

        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir);
        jButtonSalir.setBounds(525, 441, 93, 23);
        jPanel1.add(jTextFieldHabServicios);
        jTextFieldHabServicios.setBounds(384, 78, 60, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo coco6.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 750, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCuartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCuartActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBoxCuartActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        try{
            
        if(this.jCheckBoxCuart.isSelected()){
                sum+=300;
            } if(this.jCheckBoxBar.isSelected()){
                sum+=400;
            } if(this.jCheckBoxTintoreria.isSelected()){
                sum+=150;
            }if(this.jCheckBoxSpa.isSelected()){
                sum+=1200;
            } if(this.jCheckBoxNiñera.isSelected()){
                sum+=600;
            }
        JOptionPane.showMessageDialog(this,"Total: "+sum);
        
        String query="update ventas, ocupaciones, habitaciones set ventas.gastosExtras=ventas.gastosExtras+"+sum+" WHERE ventas.id=ocupaciones.Ventas_id	and habitaciones.numero=ocupaciones.habitaciones_numero and habitaciones.numero="+"'"+this.jTextFieldHabServicios.getText().trim()+"'";
        

        
        int j=this.conn.Update(query);//Ejecuta accion de alta en la BD
        System.out.println("Numero de registros afectados por la accion"+j);
        this.jCheckBoxCuart.setSelected(false);
        this.jCheckBoxBar.setSelected(false);
        this.jCheckBoxTintoreria.setSelected(false);
        this.jCheckBoxSpa.setSelected(false);
        this.jCheckBoxNiñera.setSelected(false);
        this.jTextFieldHabServicios.setText("");
        sum=0;
        }catch (Exception e) {
            System.out.println(e);
            
        }
        
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCheckBoxBar;
    private javax.swing.JCheckBox jCheckBoxCuart;
    private javax.swing.JCheckBox jCheckBoxNiñera;
    private javax.swing.JCheckBox jCheckBoxSpa;
    private javax.swing.JCheckBox jCheckBoxTintoreria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldHabServicios;
    // End of variables declaration//GEN-END:variables
}
