/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clasesChekin;

import controlMySql.MySqlConn;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author andyr
 */
public final class Mapa extends javax.swing.JFrame {
    int piso;
    String tipo;
    ArrayList <Integer> desocupados = new ArrayList();
    MySqlConn objConn=new  MySqlConn();
    /**
     * Creates new form Mapa
     */
    public Mapa(int piso,String tipo) {
        initComponents();
        this.piso = piso;
        this.tipo = tipo;
        desocupados = checa();
        if(piso == 1){
            piso1(tipo);
        }else{
            piso2(tipo);
        }
    }
    
    public Mapa() {
        //this(1,"");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel5");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("jLabel7");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("jLabel9");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("jLabel10");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("jLabel11");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("jLabel12");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("jLabel13");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("jLabel14");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("jLabel15");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(97, 97, 97))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public ArrayList checa(){
       ArrayList <Integer> lista = null;
        ArrayList <Object> datosTabla;
    
        String query="Select * from habitaciones";
        objConn.Consult(query);
        int n=0;
        int i,j;
        if(objConn.rs!=null){
            try{
                objConn.rs.last(); //se posiciona en el ultimo registros de la tabla
                n=objConn.rs.getRow(); //regresa el numero actual del registro
                objConn.rs.first();
            }catch(Exception e){}
                lista = new ArrayList ();
                boolean o;
                int nu;
            for(i=0;i<n;i++){ //n total de registros                
                    try{
                      o = objConn.rs.getBoolean(3);
                      if (o == true){
                          nu = objConn.rs.getInt(1);
                          lista.add(nu);
                      }    
                    }catch(Exception e){ }
                try{
                    objConn.rs.next();
                }catch(Exception e){}
            }
           
        objConn.closeRsStmt();
        objConn.closeConnection();

        }
       return lista; 
    }
    
    public void piso1(String tipo){
        this.jLabel1.setText("1");
        this.jLabel2.setText("2");
        this.jLabel3.setText("3");
        this.jLabel4.setText("4");
        this.jLabel5.setText("5");
        this.jLabel6.setText("6");
        this.jLabel7.setText("7");
        this.jLabel8.setText("8");
        this.jLabel9.setText("9");
        this.jLabel10.setText("10");
        this.jLabel11.setText("11");
        this.jLabel12.setText("12");
        this.jLabel13.setText("13");
        this.jLabel14.setText("14");
        this.jLabel15.setText("15");
        if(tipo == "sencilla"){
            if(!des(1)){
                this.jLabel1.setBackground(Color.ORANGE);
            }
            if(!des(2)){
                this.jLabel2.setBackground(Color.ORANGE);
            }
            if(!des(3)){
                this.jLabel3.setBackground(Color.ORANGE);
            }
            if(!des(4)){
                this.jLabel4.setBackground(Color.ORANGE);
            }
            if(!des(5)){
                this.jLabel5.setBackground(Color.ORANGE);
            }
            if(!des(6)){
                this.jLabel6.setBackground(Color.ORANGE);
            }
            if(!des(7)){
                this.jLabel7.setBackground(Color.ORANGE);
            }
            if(!des(8)){
                this.jLabel8.setBackground(Color.ORANGE);
            }
            if(!des(9)){
                this.jLabel9.setBackground(Color.ORANGE);
            }
            if(!des(10)){
                this.jLabel10.setBackground(Color.ORANGE);
            }
            this.jLabel11.setBackground(Color.cyan);
            this.jLabel12.setBackground(Color.cyan);
            this.jLabel13.setBackground(Color.cyan);
            this.jLabel14.setBackground(Color.cyan);
            this.jLabel15.setBackground(Color.yellow);
        }else if (tipo == "deluxe"){
            this.jLabel1.setBackground(Color.ORANGE);
            this.jLabel2.setBackground(Color.ORANGE);
            this.jLabel3.setBackground(Color.ORANGE);
            this.jLabel4.setBackground(Color.ORANGE);
            this.jLabel5.setBackground(Color.ORANGE);
            this.jLabel6.setBackground(Color.ORANGE);
            this.jLabel7.setBackground(Color.ORANGE);
            this.jLabel8.setBackground(Color.ORANGE);
            this.jLabel9.setBackground(Color.ORANGE);
            this.jLabel10.setBackground(Color.ORANGE);
            
            if(!des(11)){
                this.jLabel11.setBackground(Color.cyan);
            }
            if(!des(12)){
                this.jLabel12.setBackground(Color.cyan);
            }
            if(!des(13)){
                this.jLabel13.setBackground(Color.cyan);
            }
            if(!des(14)){
                this.jLabel14.setBackground(Color.cyan);
            }
            
            this.jLabel15.setBackground(Color.yellow);
        }else{
            this.jLabel1.setBackground(Color.ORANGE);
            this.jLabel2.setBackground(Color.ORANGE);
            this.jLabel3.setBackground(Color.ORANGE);
            this.jLabel4.setBackground(Color.ORANGE);
            this.jLabel5.setBackground(Color.ORANGE);
            this.jLabel6.setBackground(Color.ORANGE);
            this.jLabel7.setBackground(Color.ORANGE);
            this.jLabel8.setBackground(Color.ORANGE);
            this.jLabel9.setBackground(Color.ORANGE);
            this.jLabel10.setBackground(Color.ORANGE);
            
            
            this.jLabel11.setBackground(Color.cyan);
            this.jLabel12.setBackground(Color.cyan);
            this.jLabel13.setBackground(Color.cyan);
            this.jLabel14.setBackground(Color.cyan);
            
            if(!des(15)){
                this.jLabel15.setBackground(Color.yellow);
            }  
        }
    }
    
    public void piso2(String tipo){
        this.jLabel1.setText("16");
        this.jLabel2.setText("17");
        this.jLabel3.setText("18");
        this.jLabel4.setText("19");
        this.jLabel5.setText("20");
        this.jLabel6.setText("21");
        this.jLabel7.setText("22");
        this.jLabel8.setText("23");
        this.jLabel9.setText("24");
        this.jLabel10.setText("25");
        this.jLabel11.setText("26");
        this.jLabel12.setText("27");
        this.jLabel13.setText("28");
        this.jLabel14.setText("29");
        this.jLabel15.setText("30");
        if(tipo == "sencilla"){
            if(!des(16)){
                this.jLabel1.setBackground(Color.ORANGE);
            }
            if(!des(17)){
                this.jLabel2.setBackground(Color.ORANGE);
            }
            if(!des(18)){
                this.jLabel3.setBackground(Color.ORANGE);
            }
            if(!des(19)){
                this.jLabel4.setBackground(Color.ORANGE);
            }
            
            this.jLabel5.setBackground(Color.cyan);
            this.jLabel6.setBackground(Color.cyan);
            this.jLabel7.setBackground(Color.cyan);
            this.jLabel8.setBackground(Color.cyan);
            this.jLabel9.setBackground(Color.cyan);
            this.jLabel10.setBackground(Color.cyan);
            this.jLabel12.setBackground(Color.cyan);
            
            this.jLabel11.setBackground(Color.yellow);
            this.jLabel13.setBackground(Color.yellow);
            this.jLabel14.setBackground(Color.yellow);
            this.jLabel15.setBackground(Color.yellow);
            
        }else if (tipo == "deluxe"){
            this.jLabel1.setBackground(Color.ORANGE);
            this.jLabel2.setBackground(Color.ORANGE);
            this.jLabel3.setBackground(Color.ORANGE);
            this.jLabel4.setBackground(Color.ORANGE);
            
            if(!des(20)){
                this.jLabel5.setBackground(Color.cyan);
            }
            if(!des(21)){
                this.jLabel6.setBackground(Color.cyan);
            }
            if(!des(22)){
                this.jLabel7.setBackground(Color.cyan);
            }
            if(!des(23)){
                this.jLabel8.setBackground(Color.cyan);
            }
            if(!des(24)){
                this.jLabel9.setBackground(Color.cyan);
            }
            if(!des(25)){
                this.jLabel10.setBackground(Color.cyan);
            }
            
            if(!des(27)){
                this.jLabel12.setBackground(Color.cyan);
            }
            
            this.jLabel11.setBackground(Color.yellow);
            this.jLabel13.setBackground(Color.yellow);
            this.jLabel14.setBackground(Color.yellow);
            this.jLabel15.setBackground(Color.yellow);
        }else{
            this.jLabel1.setBackground(Color.ORANGE);
            this.jLabel2.setBackground(Color.ORANGE);
            this.jLabel3.setBackground(Color.ORANGE);
            this.jLabel4.setBackground(Color.ORANGE);
            
            this.jLabel5.setBackground(Color.cyan);
            this.jLabel6.setBackground(Color.cyan);
            this.jLabel7.setBackground(Color.cyan);
            this.jLabel8.setBackground(Color.cyan);
            this.jLabel9.setBackground(Color.cyan);
            this.jLabel10.setBackground(Color.cyan);
            this.jLabel12.setBackground(Color.cyan);
            
            if(!des(26)){
                this.jLabel11.setBackground(Color.yellow);
            } 
            if(!des(28)){
                this.jLabel13.setBackground(Color.yellow);
            } 
            if(!des(29)){
                this.jLabel14.setBackground(Color.yellow);
            } 
            if(!des(30)){
                this.jLabel15.setBackground(Color.yellow);
            }  
        }
    }
    
    public boolean des(int n){
        boolean r = true;
        int aux;
        for(int i=0 ; i<desocupados.size() ; i++){
            aux = desocupados.get(i);
            if (aux == n){
                r = false;
            }
        }
        return r;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
